GET http://localhost:3001/api/v1/admin/stats
Accept: application/json

# Response:
#HTTP/1.1 200 OK
#Date: Tue, 22 Mar 2022 15:03:27 GMT
#Content-Length: 86
#Content-Type: text/plain; charset=utf-8
#
#{"proxies_running":1,"stats":[{"ID":"some_name","Addr":"[::]:30081","Connections":0}]}
###

POST http://localhost:3001/api/v1/tunnel
Accept: application/json

{
  "name": "some_name"
}

# Response:
#HTTP/1.1 200 OK
#Date: Tue, 22 Mar 2022 14:21:54 GMT
#Content-Length: 94
#Content-Type: text/plain; charset=utf-8
#
# {"id":"some_name","proxy_endpoint_url":"http://some_name.localhost:30081","client_url":"http://some_name.localhost:3001","max_conn_count":10}


###
DELETE http://localhost:3001/api/v1/tunnel/some_name
Accept: application/json

{
  "name": "some_name"
}

# Response:
#HTTP/1.1 200 OK
#Date: Tue, 22 Mar 2022 14:21:54 GMT
#Content-Length: 94
#Content-Type: text/plain; charset=utf-8
#
#{"id":"some_name","port":30039,"url":"http://vkurupifvi.localhost:3001","max_conn_count":10}


###
